## Switches
set_property PACKAGE_PIN V10 [get_ports {SW3[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW3[3]}]
set_property PACKAGE_PIN U11 [get_ports {SW3[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW3[2]}]
set_property PACKAGE_PIN U12 [get_ports {SW3[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW3[1]}]
set_property PACKAGE_PIN H6 [get_ports {SW3[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW3[0]}]
set_property PACKAGE_PIN T13 [get_ports {SW2[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW2[3]}]
set_property PACKAGE_PIN R16 [get_ports {SW2[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW2[2]}]
set_property PACKAGE_PIN U8 [get_ports {SW2[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW2[1]}]
set_property PACKAGE_PIN T8 [get_ports {SW2[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW2[0]}]
set_property PACKAGE_PIN R13 [get_ports {SW1[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW1[3]}]
set_property PACKAGE_PIN U18 [get_ports {SW1[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW1[2]}]
set_property PACKAGE_PIN T18 [get_ports {SW1[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW1[1]}]
set_property PACKAGE_PIN R17 [get_ports {SW1[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW1[0]}]
set_property PACKAGE_PIN R15 [get_ports {SW0[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW0[3]}]
set_property PACKAGE_PIN M13 [get_ports {SW0[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW0[2]}]
set_property PACKAGE_PIN L16 [get_ports {SW0[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW0[1]}]
set_property PACKAGE_PIN J15 [get_ports {SW0[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SW0[0]}]

## Botones que controlan el grupo de Switches
set_property PACKAGE_PIN M18 [get_ports {BTN[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {BTN[0]}]
set_property PACKAGE_PIN M17 [get_ports {BTN[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {BTN[1]}]

## Ánodos de display 7 segmentos 
set_property PACKAGE_PIN J17 [get_ports {AN[7]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]
set_property PACKAGE_PIN J18 [get_ports {AN[6]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property PACKAGE_PIN T9 [get_ports {AN[5]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property PACKAGE_PIN J14 [get_ports {AN[4]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property PACKAGE_PIN P14 [get_ports {AN[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property PACKAGE_PIN T14 [get_ports {AN[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property PACKAGE_PIN K2 [get_ports {AN[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property PACKAGE_PIN U13 [get_ports {AN[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]

## Display de 7 segmentos
set_property PACKAGE_PIN T10 [get_ports {SEG[0]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property PACKAGE_PIN R10 [get_ports {SEG[1]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property PACKAGE_PIN K16 [get_ports {SEG[2]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property PACKAGE_PIN K13 [get_ports {SEG[3]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property PACKAGE_PIN P15 [get_ports {SEG[4]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property PACKAGE_PIN T11 [get_ports {SEG[5]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property PACKAGE_PIN L18 [get_ports {SEG[6]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property PACKAGE_PIN H15 [get_ports {SEG[7]}]; set_property IOSTANDARD LVCMOS33 [get_ports {SEG[7]}]
